spring.datasource.url=jdbc:mysql://revshop.cjqoymqow51x.ap-south-1.rds.amazonaws.com:3306/revshop?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=Bharadwaj2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true